In [22]:
import traceback


def green(s):
    return '\033[1;32m%s\033[m' % s


def yellow(s):
    return '\033[1;33m%s\033[m' % s


def red(s):
    return '\033[1;31m%s\033[m' % s


def log(*m):
    print(" ".join(map(str, m)))


def log_exit(*m):
    log(red("ERROR:"), *m)
    exit(1)


def check_numpy():
    try:
        import numpy
        log(green("PASS"), "NumPy installed")
    except ModuleNotFoundError:
        log(red("FAIL"), "NumPy not installed")


def check_scipy():
    try:
        import scipy
        log(green("PASS"), "SciPy installed")
    except ModuleNotFoundError:
        log(red("FAIL"), "SciPy not installed")


def check_matplotlib():
    try:
        import matplotlib
        log(green("PASS"), "matplotlib installed")
    except ModuleNotFoundError:
        log(red("FAIL"), "matplotlib not installed")


def check_torch():
    try:
        import torch
        log(green("PASS"), "PyTorch installed")
    except ModuleNotFoundError:
        log(red("FAIL"), "PyTorch not installed")


def check_tqdm():
    try:
        import tqdm
        log(green("PASS"), "tqdm installed")
    except ModuleNotFoundError:
        log(red("FAIL"), "tqdm not installed")


def main():
    try:
        check_numpy()
        check_scipy()
        check_matplotlib()
        check_torch()
        check_tqdm()
    except Exception:
        log_exit(traceback.format_exc())


if __name__ == "__main__":
    main()

PASS NumPy installed
PASS SciPy installed
PASS matplotlib installed
PASS PyTorch installed
PASS tqdm installed


In [12]:
import numpy as np

def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    #Your code here
    arr=np.random.rand(n,1)
    return arr

In [13]:
z=randomization(5)

In [14]:
z

array([[0.5335035 ],
       [0.54739015],
       [0.11052622],
       [0.06616966],
       [0.59760459]])

In [15]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    #Your code here
    A = np.random.rand(h, w)
    B = np.random.rand(h, w)
    s = A+B
    return A,B,s

In [16]:
a,b,c= operations(4,5)

In [17]:
a

array([[0.51142379, 0.20325304, 0.13449059, 0.9053437 , 0.40518562],
       [0.57275975, 0.81276706, 0.33163493, 0.62703785, 0.23032583],
       [0.23720143, 0.97695893, 0.94878482, 0.41017182, 0.71174762],
       [0.86544077, 0.2157343 , 0.26688707, 0.68972757, 0.02147381]])

In [18]:
b

array([[0.24890024, 0.05296095, 0.88703914, 0.76266203, 0.40828716],
       [0.3223995 , 0.07313882, 0.41041203, 0.40649327, 0.5770882 ],
       [0.34790307, 0.7924397 , 0.9881574 , 0.64159799, 0.78592748],
       [0.83511651, 0.78159997, 0.43650863, 0.19970185, 0.99906861]])

In [19]:
c

array([[0.76032403, 0.25621399, 1.02152973, 1.66800573, 0.81347277],
       [0.89515925, 0.88590588, 0.74204696, 1.03353112, 0.80741403],
       [0.5851045 , 1.76939863, 1.93694222, 1.05176981, 1.49767509],
       [1.70055728, 0.99733427, 0.7033957 , 0.88942942, 1.02054241]])

In [21]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    #Your code here
    s = np.linalg.norm(A+B)
    return s

In [24]:
a1=randomization(5)
a2=randomization(5)
norm(a1,a2)

2.589956497011694

In [26]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    #Your code here
    mul=np.matmul(weights.transpose(),inputs)
    out=np.tanh(mul)
    return out

In [46]:
inputs=np.array([0,0,1])
weights=2 * np.random.random((3, 1)) - 1
out=neural_network(inputs, weights)


In [47]:
weights=2 * np.random.random((3, 1)) - 1

In [48]:
weights.transpose()

array([[-0.61099253,  0.13431091,  0.48210929]])

In [49]:
inputs

array([0, 0, 1])

In [50]:
out

array([0.52048883])

In [27]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    if(x<=y):
        return x*y
    else:
        return x/y

In [31]:
def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y
    """
    out = np.vectorize(scalar_function)
    return out(x,y)

In [33]:
scalar_function(5,4)

1.25

In [34]:
vector_function(4,5)

array(20)